### ISSUE TITLE
MER on a DVB-T device

### ISSUE THREAD

**Issue by PAk-CatchFire** [dsoprea/ZapLib#1]
Hi, I am involved in a project where we need to get MER from a DVB-T signal (in Europe). Do you think I could achieve this with your library?

Best regards

**Comment by dsoprea** [comment]
We only wrap the Ubuntu _dvb-apps_ package. First figure out if the azap/szap/czap/tzap (probably szap) supports it. Then, we can figure out if it's available through this library or how to add it.

I'm not familiar with MER, so I don't know:

- if there is MER data, whether we get the normal SNR *as well* as MER or _instead_ of it.
- if MER data should be available during the scan or/and the actual tuning. 
- if MER is available with the rest of the information reported or if it is retrieved through some other channel.

Most of this can be answered by playing with the command-line tools and just looking at the output that the scan and/or the zap executables print to the screen if you have the tuner and connection to your local system, which is not something that I'm equipped with for satellite.

On Ubuntu, install the tools with `sudo apt-get install dvb-apps`.

https://www.linuxtv.org/wiki/index.php/LinuxTV_dvb-apps
